use_frameworks!

platform :ios, '9.0'

target 'HYLibrary_Example' do
  pod 'HYLibrary', :path => '../'

  target 'HYLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
