use_frameworks!

source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'


platform :ios, '12.0'

project 'HYLibrary.xcodeproj'

target 'HYLibrary_Example' do
  pod 'HYLibrary', :path => '../'
  pod 'HYAppInfo', :path => '../../AppInfo/'
  pod 'Masonry'

  pod 'MGJRouter', :git => 'https://github.com/hillyoung/MGJRouter.git'
  pod 'YYModel'
  pod 'OpenSSL-Universal'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end

target 'CleanDemo' do
#  pod 'HYLibrary', :path => '../'
  pod 'HYAppInfo', :path => '../../AppInfo/'
  pod 'Masonry'
#  pod 'openssl'
  pod 'GMEllipticCurveCrypto'
end
