use_frameworks!

platform :ios, '9.0'

target 'HYLibrary_Example' do
  pod 'HYLibrary', :path => '../'

  pod 'MGJRouter', :git => 'https://github.com/hillyoung/MGJRouter.git'
  pod 'YYModel'

  target 'HYLibrary_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
